version: '3.9'
x-arat-api-common:
  &arat-api-common
  build: ./arat_api
  env_file:
     - ./arat_api/.env
  volumes:
    - ./arat_api:/app
  working_dir: /app
  depends_on:
    - db
services:
  api-init:
    << : *arat-api-common
    container_name: arat_api_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pwd
        ls
        elixir -v
        mix ecto.create
        mix deps.get
  api:
    << : *arat-api-common
    container_name: arat_api
    entrypoint: /bin/bash
    restart: always
    ports:
      - '4000:4000'
    command:
      - -c
      - |
        pwd
        ls
        elixir -v
        mix phx.server
  web:
    container_name: arat_web
    build: ./arat_web/
    env_file: ./arat_web/.env
    entrypoint: /bin/bash
    ports:
      - '3000:3000'
    command:
      - -c
      - |
        pwd
        ls
        node --version
        yarn --version
        yarn install
        yarn dev -o
    volumes:
      - ./arat_web:/app
  db:
    image: postgres:14.5
    container_name: arat_db
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: arat
      POSTGRES_PASSWORD: arat123
      POSTGRES_DB: arat
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
